### ISSUE TITLE
'numpy.ndarray' object has no attribute 'tags'

### ISSUE THREAD

**Issue by zhaoy99** [linanqiu/word2vec-sentiments#6]
with Python 2.7.3, SciPy 0.15.1,  Gensim 0.12.1, and NumPy 1.10.1, I ran into the error below
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/vagrant/ve2/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 701, in worker_loop
    if not worker_one_job(job, init):
  File "/vagrant/ve2/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 692, in worker_one_job
    tally, raw_tally = self._do_train_job(items, alpha, inits)
  File "/vagrant/ve2/local/lib/python2.7/site-packages/gensim/models/doc2vec.py", line 638, in _do_train_job
    indexed_doctags = self.docvecs.indexed_doctags(doc.tags)
AttributeError: 'numpy.ndarray' object has no attribute 'tags'

**Comment by zhaoy99** [comment]
It would be great to have all the lines in README in a single py file.

**Comment by linanqiu** [comment]
https://github.com/linanqiu/word2vec-sentiments/issues/5

Doesth is help?

**Comment by linanqiu** [comment]
There's a closed issue with this error

**Comment by linanqiu** [comment]
Fixed this in the latest version
